let selected='해양 쓰레기', emoji='🧴', position=null, map, markers=[];
const points=()=>Number(localStorage.getItem('bosoPoints')||120); const reports=()=>JSON.parse(localStorage.getItem('bosoReports')||'[]');
function savePoints(v){localStorage.setItem('bosoPoints',v);document.querySelectorAll('#points,#pointsLarge').forEach(e=>e.textContent=v+' P')}
function showTab(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='map')setTimeout(initMap,50);window.scrollTo(0,0)}
function chooseCategory(c,e){selected=c;emoji=e;document.getElementById('selectedCategory').textContent=c;document.getElementById('selectedEmoji').textContent=e;showTab('report');getLocation()}
function getLocation(){const out=document.getElementById('locationText');out.textContent='위치를 확인 중입니다…';navigator.geolocation?.getCurrentPosition(p=>{position=[p.coords.latitude,p.coords.longitude];out.textContent=`현재 위치 · ${p.coords.latitude.toFixed(4)}, ${p.coords.longitude.toFixed(4)}`;document.getElementById('office').textContent='부산지방해양수산청 / 관할 구청'},()=>{position=[35.1595,129.1604];out.textContent='부산 해운대구 우동 (예시 위치)';document.getElementById('office').textContent='해운대구청 해양관리과'} ,{enableHighAccuracy:true,timeout:8000})|| (out.textContent='위치 권한을 허용해 주세요')}
function previewPhoto(input){const f=input.files[0];if(!f)return;const img=document.getElementById('preview');img.src=URL.createObjectURL(f);img.style.display='block';document.getElementById('photoPrompt').style.display='none'}
async function analyzeImage(){const image=document.getElementById('preview'),result=document.getElementById('aiResult'),button=document.getElementById('aiCheck');if(!image.src){toast('판별할 사진을 먼저 추가해 주세요.');return}if(!window.cocoSsd){toast('AI 분석기를 불러오는 중입니다. 잠시 후 다시 시도해 주세요.');return}button.disabled=true;button.textContent='AI가 사진을 분석하고 있어요…';result.hidden=false;result.className='ai-result';result.textContent='이미지 속 물체를 확인 중입니다.';try{const model=await cocoSsd.load();const predictions=await model.detect(image);const waste=['bottle','cup','wine glass','fork','knife','spoon','bowl'];const found=predictions.filter(p=>waste.includes(p.class));if(found.length){const words={bottle:'플라스틱 병',cup:'컵','wine glass':'유리병',fork:'식기',knife:'식기',spoon:'식기',bowl:'용기'};const labels=found.map(p=>words[p.class]).join(', ');result.innerHTML=`<b>✓ 해양 쓰레기 가능성이 높아요.</b><br>감지된 물체: ${labels}<br>현장 상태를 확인한 뒤 제보해 주세요.`;if(!document.getElementById('description').value)document.getElementById('description').value=`AI 감지 결과: ${labels}`}else{result.className='ai-result warning';result.innerHTML='<b>! 쓰레기 후보를 명확히 찾지 못했어요.</b><br>훼손·오염 상태에 따라 인식이 어려울 수 있습니다. 현장을 확인해 제보할 수 있어요.'}}catch(e){result.className='ai-result warning';result.textContent='AI 분석기를 불러오지 못했습니다. 인터넷 연결 후 다시 시도해 주세요.'}finally{button.disabled=false;button.textContent='✦ AI로 해양 쓰레기 판별하기'}}
function submitReport(){if(!position){toast('위치 정보를 먼저 확인해 주세요.');return}const r={id:Date.now(),category:selected,emoji,description:document.getElementById('description').value||'시민 제보',pos:position,date:new Date().toLocaleDateString('ko-KR')};const all=reports();all.unshift(r);localStorage.setItem('bosoReports',JSON.stringify(all));savePoints(points()+20);renderReports();toast('제보가 전달되었습니다! +20P 적립');setTimeout(()=>showTab('home'),700)}
function renderReports(){const root=document.getElementById('recent'),all=reports();document.getElementById('mapCount').textContent=all.length;if(!all.length){root.innerHTML='<p class="empty">아직 제보한 내용이 없어요.</p>';return}root.innerHTML=all.slice(0,3).map(r=>`<div class="report-item"><span class="r-icon">${r.emoji}</span><div><b>${r.category}</b><small>${r.date} · 처리 중</small></div><span class="badge">접수완료</span></div>`).join('')}
function initMap(){if(!map){map=L.map('leafletMap',{zoomControl:false}).setView([35.1595,129.1604],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map)}markers.forEach(m=>m.remove());markers=reports().map(r=>L.marker(r.pos).addTo(map).bindPopup(`<b>${r.emoji} ${r.category}</b><br>${r.description}<br><small>처리 중</small>`));if(markers.length)map.setView(reports()[0].pos,13);map.invalidateSize()}
function redeem(cost,name){if(points()<cost){toast(`포인트가 ${cost-points()}P 부족해요.`);return}const phone=prompt(`${name} 교환 신청\n상품을 받을 휴대폰 번호를 입력해 주세요.`);if(phone){savePoints(points()-cost);toast('교환 신청이 완료되었습니다. (프로토타입)')}}
function toast(m){const e=document.getElementById('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
savePoints(points());renderReports();
// file://로 직접 열 때는 서비스 워커가 허용되지 않으므로 앱 실행을 막지 않도록 제외합니다.
if(location.protocol!=='file:'&&'serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
document.querySelector('[data-tab="rewards"]').lastChild.textContent='포인트 상점';
var g=document.querySelector('.rewards'),p=[['친환경 텀블러',8000,'file:///C:/Users/안녕하세요/Downloads/thumb-69a3cb3e9ac32_568x568.jpg'],['대나무 칫솔',2000,'file:///C:/Users/안녕하세요/Downloads/image%20(1).png'],['CU 모바일 상품권 3,000원',3000,'file:///C:/Users/안녕하세요/Downloads/IMG_9847.jpeg'],['CU 모바일 상품권 5,000원',5000,'file:///C:/Users/안녕하세요/Downloads/IMG_9847.jpeg'],['CU 모바일 상품권 10,000원',10000,'file:///C:/Users/안녕하세요/Downloads/IMG_9847.jpeg'],['GS25 모바일 상품권 3,000원',3000,'file:///C:/Users/안녕하세요/Downloads/image.png'],['GS25 모바일 상품권 5,000원',5000,'file:///C:/Users/안녕하세요/Downloads/image.png'],['GS25 모바일 상품권 10,000원',10000,'file:///C:/Users/안녕하세요/Downloads/image.png']];g.innerHTML='';p.forEach(function(x){var a=document.createElement('article'),d=document.createElement('div'),i=document.createElement('img'),b=document.createElement('b'),q=document.createElement('p'),z=document.createElement('button');d.className='reward-img';i.src=x[2];i.alt=x[0];i.style.cssText='width:100%;height:100%;object-fit:contain';d.append(i);b.textContent=x[0];q.textContent=x[1].toLocaleString()+' P';z.textContent='교환하기';z.onclick=function(){redeem(x[1],x[0])};a.append(d,b,q,z);g.append(a)});
// 상점 카드, 제보 선택창, 포인트 적립 규칙
var extraStyle=document.createElement('style');extraStyle.textContent='.rewards article{display:flex;flex-direction:column;gap:6px;min-height:230px}.rewards .reward-img{height:108px;background:#fff;overflow:hidden;flex:none}.rewards article>b{min-height:36px;font-size:12px;line-height:1.45}.rewards article p{margin:0}.rewards article button{margin-top:auto}.report-choice{position:fixed;inset:0;background:#07363aa8;z-index:40;display:grid;place-items:center;padding:20px}.choice-box{width:min(460px,100%);background:#fff;border-radius:22px;padding:23px}.choice-box h2{margin:0 0 6px}.choice-box p{font-size:12px;color:#6c8588;margin:0 0 16px}.choice-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.choice-grid button{border:1px solid #dcebed;background:#fff;border-radius:13px;padding:15px;text-align:left;color:#16373c;font:700 13px inherit}.choice-grid span{font-size:23px;display:block;margin-bottom:6px}.choice-close{float:right;border:0;background:none;font-size:23px;color:#597477}';document.head.appendChild(extraStyle);
var reportNav=document.querySelector('.report-nav');reportNav.onclick=function(){openReportChoice()};
function openReportChoice(){var overlay=document.createElement('div');overlay.className='report-choice';overlay.innerHTML='<div class="choice-box"><button class="choice-close" aria-label="닫기">×</button><h2>무엇을 제보하시나요?</h2><p>발견한 문제의 종류를 선택해 주세요.</p><div class="choice-grid"></div></div>';var options=[['해양 쓰레기','🧴'],['동물 사체','🐋'],['시설물 파손','⚠️'],['인명 위험','🆘']];options.forEach(function(o){var b=document.createElement('button');b.innerHTML='<span>'+o[1]+'</span>'+o[0];b.onclick=function(){overlay.remove();chooseCategory(o[0],o[1])};overlay.querySelector('.choice-grid').appendChild(b)});overlay.querySelector('.choice-close').onclick=function(){overlay.remove()};document.body.appendChild(overlay)}
submitReport=function(){var photo=document.getElementById('photo');if(!photo.files||!photo.files.length){toast('현장 사진을 추가한 뒤 제보해 주세요.');return}if(!position){toast('위치 정보를 먼저 확인해 주세요.');return}var r={id:Date.now(),category:selected,emoji:emoji,description:document.getElementById('description').value||'시민 제보',pos:position,date:new Date().toLocaleDateString('ko-KR'),resolved:false};var all=reports();all.unshift(r);localStorage.setItem('bosoReports',JSON.stringify(all));savePoints(points()+25);renderReports();toast('제보가 전달되었습니다! +25P 적립');setTimeout(function(){showTab('home')},700)};
renderReports=function(){var root=document.getElementById('recent'),all=reports();document.getElementById('mapCount').textContent=all.length;if(!all.length){root.innerHTML='<p class="empty">아직 제보한 내용이 없어요.</p>';return}root.innerHTML=all.slice(0,3).map(function(r){return '<div class="report-item"><span class="r-icon">'+r.emoji+'</span><div><b>'+r.category+'</b><small>'+r.date+' · '+(r.resolved?'해결완료':'처리 중')+'</small></div>'+(r.resolved?'<span class="badge">+150P 지급</span>':'<button class="resolve" onclick="confirmResolved('+r.id+')">해결 확인</button>')+'</div>'}).join('')};
function confirmResolved(id){var all=reports(),r=all.find(function(x){return x.id===id});if(!r||r.resolved)return;r.resolved=true;localStorage.setItem('bosoReports',JSON.stringify(all));savePoints(points()+150);renderReports();toast('해결 완료가 확인되어 +150P 적립!')}
renderReports();
// 적립 안내와 위치 권한
document.querySelector('.notice p').innerHTML='<b>신고하면 +25P</b><br>문제 해결 확인 시 +150P가 추가돼요.';
var permissionButton=document.createElement('button');permissionButton.className='location-permission';permissionButton.textContent='위치 권한 허용';permissionButton.onclick=function(){getLocation()};document.querySelector('.location').after(permissionButton);
getLocation=function(){var out=document.getElementById('locationText');out.textContent='GPS 위치를 확인 중입니다…';if(!navigator.geolocation){out.textContent='이 브라우저에서는 GPS 위치를 지원하지 않습니다.';return}navigator.geolocation.getCurrentPosition(function(p){position=[p.coords.latitude,p.coords.longitude];out.textContent='위도 '+p.coords.latitude.toFixed(6)+' · 경도 '+p.coords.longitude.toFixed(6);document.getElementById('office').textContent='GPS 좌표가 제보 내용에 포함됩니다.'},function(){out.textContent='위치 권한이 필요합니다. “위치 권한 허용”을 눌러 다시 시도해 주세요.'},{enableHighAccuracy:true,timeout:10000,maximumAge:0})};
getLocation=function(){var out=document.getElementById('locationText'),office=document.getElementById('office');out.textContent='GPS 위치를 확인 중입니다…';if(!navigator.geolocation){out.textContent='이 브라우저는 GPS 위치를 지원하지 않습니다.';return}navigator.geolocation.getCurrentPosition(function(p){position=[p.coords.latitude,p.coords.longitude];out.textContent='위도 '+p.coords.latitude.toFixed(6)+' · 경도 '+p.coords.longitude.toFixed(6);office.textContent='GPS 좌표가 제보 내용에 포함됩니다.';toast('현재 GPS 위치를 확인했습니다.')},function(error){position=null;var message=error.code===1?'위치 권한이 차단되어 있습니다. 브라우저 주소창의 자물쇠/설정에서 위치를 “허용”으로 바꾼 뒤 다시 눌러 주세요.':error.code===2?'현재 위치를 찾지 못했습니다. Wi‑Fi 또는 GPS를 켠 뒤 다시 시도해 주세요.':'위치 확인 시간이 초과되었습니다. 잠시 후 다시 눌러 주세요.';out.textContent=message;office.textContent='정확한 GPS 위치 확인 후 제보할 수 있습니다.';toast(message)},{enableHighAccuracy:true,timeout:20000,maximumAge:0})};
function addActivity(type,detail,points){var list=JSON.parse(localStorage.getItem('bosoActivity')||'[]');list.unshift({type:type,detail:detail,points:points,date:new Date().toLocaleString('ko-KR')});localStorage.setItem('bosoActivity',JSON.stringify(list))};
var oldSubmit=submitReport;submitReport=function(){var before=reports().length;oldSubmit();if(reports().length>before)addActivity('제보 접수','신고가 접수되어 처리 상태를 확인할 수 있어요.',25)};
var oldConfirm=confirmResolved;confirmResolved=function(id){var all=reports(),item=all.find(function(x){return x.id===id});if(!item||item.resolved)return;oldConfirm(id);addActivity('문제 해결 확인',item.category+' 제보가 해결 완료되었습니다.',150)};
var historyButton=document.createElement('button');historyButton.className='history-button';historyButton.textContent='내 적립 · 제보 내역 보기';historyButton.onclick=function(){openHistory()};document.querySelector('.report-list').appendChild(historyButton);
function openHistory(){var modal=document.createElement('div');modal.className='history-modal';var activities=JSON.parse(localStorage.getItem('bosoActivity')||'[]'),reportRows=reports().map(function(r){return '<li><b>'+r.emoji+' '+r.category+'</b><span>'+(r.resolved?'해결완료 · +150P 지급':'처리 중')+'</span></li>'}).join('')||'<li>아직 제보 내역이 없어요.</li>',pointRows=activities.map(function(a){return '<li><b>'+a.type+'</b><span>'+a.detail+'　<em>+'+a.points+'P</em></span></li>'}).join('')||'<li>아직 적립 내역이 없어요.</li>';modal.innerHTML='<div class="history-box"><button class="history-close">×</button><h2>내 활동 내역</h2><h3>사건 처리 상태</h3><ul>'+reportRows+'</ul><h3>포인트 적립 내역</h3><ul>'+pointRows+'</ul></div>';modal.querySelector('.history-close').onclick=function(){modal.remove()};document.body.appendChild(modal)}
var activityStyle=document.createElement('style');activityStyle.textContent='.location-permission,.history-button{border:1px solid #9bcdd1;background:#effafa;color:#007a88;border-radius:10px;padding:10px 12px;font:700 12px inherit;margin-top:10px}.history-button{width:100%;margin-top:14px}.history-modal{position:fixed;inset:0;background:#062d3288;z-index:50;display:grid;place-items:center;padding:20px}.history-box{position:relative;width:min(480px,100%);max-height:80vh;overflow:auto;background:#fff;border-radius:20px;padding:22px}.history-box h2{margin-top:0}.history-box h3{font-size:13px;margin:20px 0 8px;color:#007a88}.history-box ul{padding:0;margin:0;list-style:none}.history-box li{padding:11px 0;border-bottom:1px solid #e6eeee;font-size:12px}.history-box li b,.history-box li span{display:block}.history-box li span{color:#6c8588;margin-top:3px}.history-box em{color:#007a88;font-style:normal;font-weight:bold}.history-close{position:absolute;right:16px;top:12px;border:0;background:none;font-size:25px}.resolve{margin-left:auto;border:0;background:#e7f5f4;color:#007a88;border-radius:8px;padding:7px;font:700 10px inherit}';document.head.appendChild(activityStyle);
var submitWithGpsNotice=submitReport;submitReport=function(){var countBefore=reports().length;submitWithGpsNotice();if(reports().length>countBefore&&position){toast('제보 전송 완료 · GPS: '+position[0].toFixed(6)+', '+position[1].toFixed(6))}};
